version: '3'
services:
 "web-application":
  build: "./Webapplication"
  ports:
   - "8080:8080"
   - "9229:9229"
  volumes:
   - "./Webapplication/src:/web-application/src"
  depends_on:
   - database
 database:
  build: ./database
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=theRootPassword
   - MYSQL_DATABASE=webAppDatabase